### ISSUE TITLE
[Signs] Essentials Signs + strange message every startup

### ISSUE THREAD

**Issue by charlieTheBotDev** [keepcalm/BukkitForge#213]
I was just testing permissions using groupmanger (because PeX didnt work when I started making the perms and I cba to swap now)

I realised that there is a /balance command and tried it, it now works.

So then I decided to try and make some signs in spawn for players to use like [Heal] and [Buy] but they don't work. I've enabled them all in the essentials config but they still don't seem to work. 

Also, thank you for fixing the dupe bug with worldguard <3 (Now all I need is the the creeper / TNT damage flags to work and I'll be happy enough to open my server :D)

BukkitForge build 88
Essentials build 2.9.6 (From BukkitForge Jenkins changelist)

Also, I get this when I start the server everything has loaded and its bugging me because it's weird and I have no idea what it means: 

2013-01-12 06:12:08 [WARNING] [BukkitForge] Method "public Class<?> getClassByName(String)" is Deprecated, and may be removed in a future version of Bukkit
org.bukkit.plugin.AuthorNagException:
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:284)
        at com.earth2me.essentials.storage.BukkitConstructor.getClassForNode(BukkitConstructor.java:418)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:321)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:183)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:142)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:128)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:423)
        at com.earth2me.essentials.storage.YamlStorageReader.load(YamlStorageReader.java:47)
        at com.earth2me.essentials.storage.AbstractDelayedYamlFileReader.run(AbstractDelayedYamlFileReader.java:37)
        at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
        at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VAsyncTask.run(B4VAsyncTask.java:54)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)

**Comment by keepcalm** [comment]
I removed the message, I'm about to get the signs working (hopefully)

**Comment by charlieTheBotDev** [comment]
Signs are still not working (Although I'm not sure if I'm just doing something wrong with them)

I place them, type the stuff the essentials page says but they are just regular signs...

BukkitForge Build 30
Essentials Build 2.9.6

**Comment by jfmherokiller** [comment]
i can report this also except the signs activate they just don't allow info to be pushed to them.

**Comment by keepcalm** [comment]
Try the latest build - I finished implementing the signs

**Comment by charlieTheBotDev** [comment]
I've just updated to the latest build (52 from jenkins link) and signs still seem not to be working.

I'm not sure if it's me/my config or if they're actually broken.

The issue currently is with the placing/creating of the signs. If you place a sign (say, [Balance]) it just sits there and doesn't change as it should. 

I'm using the sign tutorial provided on the essentials page (http://ess.khhq.net/wiki/Sign_Tutorial) as well as the most recent version of essentials (2.9.6) from the bukkitdev page

**Comment by SpoonsJTD** [comment]
Signs may be fixed now, try the latest build again please (64+).

**Comment by charlieTheBotDev** [comment]
Just tried Essentials signs with build 65.
This is what happens when I make signs of any type:

http://imgur.com/a/MbBfI

Also, when I try signs that are more than one line I get 'Error: Invalid Charge'
I can't see any errors in the logs either.

Edit: 
Just tried Lockette and that seems to work on normal chests, haven't tried anything else as of yet. Looks like this is possibly just an issue with essentials signs.

**Comment by DrFestus** [comment]
I'm having the same problem as Chazdude42 with Essentials signs. After creating they appear with a !?

Using build 75

**Comment by charlieTheBotDev** [comment]
This is still an issue with build 110 and Essentials 2.9.6.

I've tested every Essentials sign and they all do the same thing.

**Comment by unrivaledneo** [comment]
guessing no one has gotten this to work yet? since command blocks dont work and no other signs plugin does cant really use bukkitforge till this is fixed (pretty much ruins the map without some sorta warp/tp in place)

**Comment by erictfkc** [comment]
i meet the same trouble as u
whatever i  enter the sign on first row it may become !?
anyone solve it?

**Comment by SpoonsJTD** [comment]
DevNote: The !? means it's being stopped at the packet handler level because the characters aren't acceptable chat characters. Looks like maybe a jar resource 'font.txt' contains the allowed characters. I am guessing that '&' and the brackets aren't allowed?

**Comment by erictfkc** [comment]
could this question be solve?

**Comment by Sageavatar** [comment]
Bukkitforge 186
Essentials2.10.15

Still not working. When given the Sign syntax
[Trade]
$5
1 dirt:10

The sign changes to 
?!                <- Should be returned blue for correct/working syntax or red for incorrect syntax
$5:0            <-   Correct
1 dirt:10       <- Correct
?!                 <- Should be player name

**Comment by HGeorge0103** [comment]
I was informed that BukkitForge doesnt work with essentials signs very well.  You have to remove BukkitForge and install CraftBukkit.  my signs no longer display "!?"

**Comment by Sageavatar** [comment]
I'd rather have BukkitForge and no Essentials Signs. But thanks anyway.

**Comment by charlieTheBotDev** [comment]
The idea behind bukkit forge is to combine craftbukkit and forge so removing bukkit forge and replacing it with craftbukkit achieves nothing........

**Comment by Maximuscr31** [comment]
As of version 227 this is still broken with signs. Is there any economy solution out there?

**Comment by unrivaledneo** [comment]
im using npc forge mod atm

**Comment by Maximuscr31** [comment]
What does npc forge mod have to do with buy/sale signs

**Comment by unrivaledneo** [comment]
"As of version 227 this is still broken with signs. Is there any economy solution out there?" Economy solution i found is npc mods

**Comment by Sageavatar** [comment]
Tried as of BF Build 230 plus the following Addons.

2013-02-13 11:49:50 [INFO] [BukkitForge] Server issued server command: plugmanvlist
2013-02-13 11:49:50 [INFO] [STDOUT] ←[37;22m[←[32;1mPlugMan←[37;22m] ←[37;22mPlugins: ←[32;1mChestShop v3.46←[37;1m, ←[32;1mEssentials vPre2.10.1.4←[37;1m, ←[32;1mGroupManager v2.0 (Pre2.10.1.4) (Phoenix)←[37;1m, ←[32;1mmcjobs v3.1.8←[37;1m, ←[32;1mmcMMO v1.4.00-beta2-b1509←[37;1m, ←[32;1mMobArena v0.94.4.94←[37;1m, ←[32;1mMobHealth v5.3.4←[37;1m, ←[32;1mPlugMan v1.7.2←[37;1m, ←[32;1mVault v1.2.22-b277

Debug (both essentials and bukkitforge debus)
Tested [balance] and [kit].

debug start
2013-02-13 11:46:24 [INFO] [Minecraft] Started debug profiling
2013-02-13 11:46:40 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.color - true
2013-02-13 11:46:40 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.magic - true
2013-02-13 11:46:40 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.format - true
2013-02-13 11:46:40 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.color - true
2013-02-13 11:46:40 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.magic - true
2013-02-13 11:46:40 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.format - true
2013-02-13 11:46:40 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.color - true
2013-02-13 11:46:40 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.magic - true
2013-02-13 11:46:40 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.format - true
2013-02-13 11:46:40 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.color - true
2013-02-13 11:46:40 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.magic - true
2013-02-13 11:46:40 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.format - true
2013-02-13 11:46:40 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.balance.create - tru
2013-02-13 11:46:50 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.color - true
2013-02-13 11:46:50 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.magic - true
2013-02-13 11:46:50 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.format - true
2013-02-13 11:46:50 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.color - true
2013-02-13 11:46:50 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.magic - true
2013-02-13 11:46:50 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.format - true
2013-02-13 11:46:50 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.color - true
2013-02-13 11:46:50 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.magic - true
2013-02-13 11:46:50 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.format - true
2013-02-13 11:46:50 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.color - true
2013-02-13 11:46:50 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.magic - true
2013-02-13 11:46:50 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.format - true
2013-02-13 11:46:50 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.mail.create - true
2013-02-13 11:47:14 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.color - true
2013-02-13 11:47:14 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.magic - true
2013-02-13 11:47:14 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.format - true
2013-02-13 11:47:14 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.color - true
2013-02-13 11:47:14 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.magic - true
2013-02-13 11:47:14 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.format - true
2013-02-13 11:47:14 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.color - true
2013-02-13 11:47:14 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.magic - true
2013-02-13 11:47:14 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.format - true
2013-02-13 11:47:14 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.color - true
2013-02-13 11:47:14 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.magic - true
2013-02-13 11:47:14 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.format - true
2013-02-13 11:47:14 [INFO] [com.earth2me.essentials.Essentials] [Essentials] checking if sageavatar has essentials.signs.kit.create - true

**Comment by Sageavatar** [comment]
Earlier today keepcalm released build 245 'fixes essentials signs'. Signs now properly create!!!!!!!!!!!!!!!!!!!!!!!!!

But there is an error when players try to use Trade, Sell, and Buy signs. This error comes through the console. 

2013-02-24 23:20:41 [SEVERE] [BukkitForge] Could not pass event PlayerInteractEv
ent to Essentials vPre2.10.1.4
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:393)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:464)
        at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.interactEvent(ForgeEventHandler.java:428)
        at net.minecraftforge.event.ASMEventHandler_86_ForgeEventHandler_interactEvent_PlayerInteractEvent.invoke(.dynamic)
        at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
        at net.minecraftforge.event.EventBus.post(EventBus.java:103)
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
        at ir.a(ItemInWorldManager.java:389)
        at iv.a(NetServerHandler.java:578)
        at fk.a(SourceFile:58)
        at cg.b(TcpConnection.java:458)
        at iv.d(NetServerHandler.java:136)
        at iw.b(NetworkListenThread.java:57)
        at ht.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
        at ho.r(DedicatedServer.java:269)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
        at fy.run(SourceFile:849)
Caused by: java.lang.IllegalArgumentException: Invalid inventory size; expected
27 or less
        at org.bukkit.craftbukkit.inventory.CraftInventory.setContents(CraftInventory.java:64)
        at com.earth2me.essentials.craftbukkit.InventoryWorkaround.addAllItems(InventoryWorkaround.java:40)
        at com.earth2me.essentials.Trade.pay(Trade.java:140)
        at com.earth2me.essentials.signs.SignBuy.onSignInteract(SignBuy.java:30)

```
    at com.earth2me.essentials.signs.EssentialsSign.onSignInteract(EssentialsSign.java:86)
    at com.earth2me.essentials.signs.SignPlayerListener.onPlayerInteract(SignPlayerListener.java:74)
    at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:391)
    ... 20 more
```

Hopefully @keepcalm this is an easy fix! Also, trade shops poroperly take money or items as they should.

**Comment by Maximuscr31** [comment]
As of version 246 everything works but the buy signs.

**Comment by Sageavatar** [comment]
As of build 251 Buy, Trade, and Sell Signs do not work.

**Comment by SpoonsJTD** [comment]
Closed this since the original issue is resolved. New issue is here: #541
