### ISSUE TITLE
WorldEdit

### ISSUE THREAD

**Issue by Wolftein** [keepcalm/BukkitForge#81]
When i hit something with the wand it won't work, also hpos1, hpos2, gives null for that reason i can't make a region and i won't be able to test futher commands

**Comment by Manawyrm** [comment]
We have just fixed the bug with marking a region.
But theres still something left...

**Comment by Tampa** [comment]
In BukkitForge or in the WE Port?

**Comment by minecrafter** [comment]
Duplicate of #29.

**Comment by Manawyrm** [comment]
in BukkitForge. Btw: VoxelSniper does work fine now ;)

**Comment by Wolftein** [comment]
hpos isn't fixed and when i select the region and do a command it says: Make a region selection first :P

**Comment by keepcalm** [comment]
yes, I know, I'm working on it... It's pretty hard to track down.

**Comment by Wolftein** [comment]
You're doing a great job @keepcalm :)

**Comment by keepcalm** [comment]
thanks

**Comment by keepcalm** [comment]
Hey, guess what? WORLDEDIT works! Thanks @Manawyrm :D
