### ISSUE TITLE
[Mystcraft] World issues

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#89]
Using towny, this is what I get for joining. 

http://pastebin.com/Ta7Zht3k

Worldedit does not work in a mystcraft world. I selected a region, did a //set 1 and it said it did it, but nothing changed. No errors as well. 

For leaving a myst world

http://pastebin.com/E965bBzK

**Comment by Manawyrm** [comment]
Hm. This bug could be related to another one from me. 
I will have a look into bug #88 ..

**Comment by shakey2** [comment]
This is just a hunch but try looking at the same coords in overworld at the area you edited in the mystcraft world and see if anything changed.

**Comment by xKillerbees** [comment]
It does change it in the main world.

**Comment by shakey2** [comment]
Yeah mystcraft is dangerous that way, things tend to appear in mystcraft worlds that should be only in overworld and vice versa.

**Comment by keepcalm** [comment]
I know why it's broken. World names aren't unique on forge. Need to use dimensions numbers this time. It's a quick fix.

And @xKillerbees, in the future, can you post one more line of your logs? Where it says 'blah.blah.blah.SomethingExcpetion: '? (one more line UP)
You have a knack for missing the crucial line ;)

**Comment by xKillerbees** [comment]
Using 41, same issue. 

One more line is just a repeat line of that error. That is how multicraft displays the errors so it's cleaner to see and filter.

**Comment by keepcalm** [comment]
The towny part? WE should now work, though. Can you post the extra line? I need it to work out what's screwing up

**Comment by xKillerbees** [comment]
Correct, neither work right.

I grabbed the log directly from the forge log generated from the txt file. Appears the same. 

http://pastebin.com/fuqzZ7cN

**Comment by xKillerbees** [comment]
03.01 18:56:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
03.01 18:56:28 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:601)
03.01 18:56:28 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03.01 18:56:28 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
03.01 18:56:28 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03.01 18:56:28 [Server] INFO at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerChangeWorld(Unknown Source)
03.01 18:56:28 [Server] INFO at com.palmergames.bukkit.towny.permissions.TownyPerms.assignPermissions(Unknown Source)
03.01 18:56:28 [Server] INFO Caused by: java.lang.NullPointerException
03.01 18:56:28 [Server] INFO at fy.run(SourceFile:849)
03.01 18:56:28 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
03.01 18:56:28 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
03.01 18:56:28 [Server] INFO at ho.r(DedicatedServer.java:270)
03.01 18:56:28 [Server] INFO at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
03.01 18:56:28 [Server] INFO at ht.b(SourceFile:30)
03.01 18:56:28 [Server] INFO at iw.b(NetworkListenThread.java:57)
03.01 18:56:28 [Server] INFO at iv.d(NetServerHandler.java:136)
03.01 18:56:28 [Server] INFO at cg.b(TcpConnection.java:454)
03.01 18:56:28 [Server] INFO at di.a(SourceFile:59)
03.01 18:56:28 [Server] INFO at iv.a(NetServerHandler.java:1107)
03.01 18:56:28 [Server] INFO at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:71)
03.01 18:56:28 [Server] INFO at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:233)
03.01 18:56:28 [Server] INFO at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:243)
03.01 18:56:28 [Server] INFO at xcompwiz.mystcraft.MystcraftPacketHandler.onPacketData(MystcraftPacketHandler.java:43)
03.01 18:56:28 [Server] INFO at xcompwiz.mystcraft.MPacketGUIMessage.handle(MPacketGUIMessage.java:34)
03.01 18:56:28 [Server] INFO at xcompwiz.mystcraft.ContainerBook.processMessage(ContainerBook.java:174)
03.01 18:56:28 [Server] INFO at xcompwiz.mystcraft.TileEntityBookDisplay.link(TileEntityBookDisplay.java:65)
03.01 18:56:28 [Server] INFO at xcompwiz.mystcraft.MystLinkController.travelEntity(MystLinkController.java:42)
03.01 18:56:28 [Server] INFO at xcompwiz.mystcraft.MystLinkController.teleportEntity(MystLinkController.java:121)
03.01 18:56:28 [Server] INFO at xcompwiz.mystcraft.LinkControllerCommon.onLinkEnd(LinkControllerCommon.java:91)
03.01 18:56:28 [Server] INFO at xcompwiz.mystcraft.LinkListenerForgeServer.onLinkEnd(LinkListenerForgeServer.java:32)
03.01 18:56:28 [Server] INFO at cpw.mods.fml.common.registry.GameRegistry.onPlayerChangedDimension(GameRegistry.java:354)
03.01 18:56:28 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.PlayerTracker.onPlayerChangedDimension(PlayerTracker.java:59)
03.01 18:56:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:470)
03.01 18:56:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:486)
03.01 18:56:28 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
03.01 18:56:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
03.01 18:56:28 [Server] INFO org.bukkit.event.EventException
03.01 18:56:28 [Server] SEVERE Could not pass event PlayerChangedWorldEvent to Towny v0.82.0.5

Happend when I join a mystcraft world. 

Worldedit also does not work with regions in the worlds. So things are the same as originally reported. Using 44

**Comment by keepcalm** [comment]
Ooh... I see the bug now.

**Comment by xKillerbees** [comment]
Still happening with 50. 

04.01 00:58:15 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
04.01 00:58:15 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:601)
04.01 00:58:15 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04.01 00:58:15 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
04.01 00:58:15 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
04.01 00:58:15 [Server] INFO at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerChangeWorld(Unknown Source)
04.01 00:58:15 [Server] INFO at com.palmergames.bukkit.towny.permissions.TownyPerms.assignPermissions(Unknown Source)
04.01 00:58:15 [Server] INFO Caused by: java.lang.NullPointerException
04.01 00:58:15 [Server] INFO at fy.run(SourceFile:849)
04.01 00:58:15 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
04.01 00:58:15 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
04.01 00:58:15 [Server] INFO at ho.r(DedicatedServer.java:270)
04.01 00:58:15 [Server] INFO at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
04.01 00:58:15 [Server] INFO at ht.b(SourceFile:30)
04.01 00:58:15 [Server] INFO at iw.b(NetworkListenThread.java:57)
04.01 00:58:15 [Server] INFO at iv.d(NetServerHandler.java:136)
04.01 00:58:15 [Server] INFO at cg.b(TcpConnection.java:454)
04.01 00:58:15 [Server] INFO at di.a(SourceFile:59)
04.01 00:58:15 [Server] INFO at iv.a(NetServerHandler.java:1107)
04.01 00:58:15 [Server] INFO at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:71)
04.01 00:58:15 [Server] INFO at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:233)
04.01 00:58:15 [Server] INFO at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:243)
04.01 00:58:15 [Server] INFO at xcompwiz.mystcraft.MystcraftPacketHandler.onPacketData(MystcraftPacketHandler.java:43)
04.01 00:58:15 [Server] INFO at xcompwiz.mystcraft.MPacketGUIMessage.handle(MPacketGUIMessage.java:34)
04.01 00:58:15 [Server] INFO at xcompwiz.mystcraft.ContainerBook.processMessage(ContainerBook.java:174)
04.01 00:58:15 [Server] INFO at xcompwiz.mystcraft.TileEntityBookDisplay.link(TileEntityBookDisplay.java:65)
04.01 00:58:15 [Server] INFO at xcompwiz.mystcraft.MystLinkController.travelEntity(MystLinkController.java:42)
04.01 00:58:15 [Server] INFO at xcompwiz.mystcraft.MystLinkController.teleportEntity(MystLinkController.java:121)
04.01 00:58:15 [Server] INFO at xcompwiz.mystcraft.LinkControllerCommon.onLinkEnd(LinkControllerCommon.java:91)
04.01 00:58:15 [Server] INFO at xcompwiz.mystcraft.LinkListenerForgeServer.onLinkEnd(LinkListenerForgeServer.java:32)
04.01 00:58:15 [Server] INFO at cpw.mods.fml.common.registry.GameRegistry.onPlayerChangedDimension(GameRegistry.java:354)
04.01 00:58:15 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.PlayerTracker.onPlayerChangedDimension(PlayerTracker.java:59)
04.01 00:58:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:470)
04.01 00:58:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:486)
04.01 00:58:15 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
04.01 00:58:15 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
04.01 00:58:15 [Server] INFO org.bukkit.event.EventException
04.01 00:58:15 [Server] SEVERE Could not pass event PlayerChangedWorldEvent to Towny v0.82.0.5

Logblock now does not record at all now since it says world not loaded.

**Comment by AlexMason** [comment]
Does this still occur? I see the issue is still open?

**Comment by mmis1000** [comment]
yes
it is not only on myscraft world
It seems happen on all world except overworld
All changes by worldedit will only happen on the overworld but not the dim the players in
I think it is because
Though world name issue is fixed in #75 ,It still can't detect what dim is the player in.
So the change is still happened in overworld
I think it may be fixed soon

**Comment by joey19982** [comment]
It says that he fixed it in build 76, but still happening for me on build 81. Strange.

**Comment by keplersj** [comment]
I think this a bug that is at the root of Bukkit. Where Forge/Vanilla save sub-worlds/dimensions inside the root save world Bukkit treats each sub-world/dimension as it's own world folder. So World, World-Nether, and World-End, World-7, would all be in the root server folder if we were porting MindCrack to Bukkit. Because we are porting Bukkit to Forge DIM, DIM-1, and DIM-7 are all inside the World folder. If I recall correctly Mystcraft had a similar issue when it was ported to CraftBukkit. Davboecki did that port. You could always ask him: https://github.com/davboecki

**Comment by shakey2** [comment]
Couldn't you just forward it to the correct folder for that world?

**Comment by keplersj** [comment]
In theory, yes. In execution, possibly. See each plugin that handles world stuff handles it a bit differently. So that causes some problems. This is where a level/world wrapper would help. It could create a sort of symbolic link to the correct location. It all depends on how someone with actual Java/Minecraft/Forge/Bukkit coding experience codes it.

**Comment by mmis1000** [comment]
2013-01-25 14:08:07 [SEVERE] [BukkitForge] Could not pass event PlayerMoveEvent to WorldGuard v5.6.5
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:397)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onPlayerMove(ForgeEventHandler.java:750)
    at net.minecraftforge.event.ASMEventHandler_70_ForgeEventHandler_onPlayerMove_PlayerMoveEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at keepcalm.mods.events.ForgeEventHelper.onPlayerMove(ForgeEventHelper.java:206)
    at iv.a(NetServerHandler.java)
    at eb.a(SourceFile:136)
    at cg.b(TcpConnection.java:454)
    at iv.d(NetServerHandler.java:141)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
    at com.sk89q.worldguard.bukkit.ConfigurationManager.get(ConfigurationManager.java:203)
    at com.sk89q.worldguard.bukkit.WorldGuardPlayerListener$PlayerMoveHandler.onPlayerMove(WorldGuardPlayerListener.java:90)
    at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:395)
    ... 19 more
2013-01-25 14:08:07 [SEVERE] [BukkitForge] Could not pass event PlayerMoveEvent to WorldGuard v5.6.5
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:397)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onPlayerMove(ForgeEventHandler.java:750)
    at net.minecraftforge.event.ASMEventHandler_70_ForgeEventHandler_onPlayerMove_PlayerMoveEvent.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at keepcalm.mods.events.ForgeEventHelper.onPlayerMove(ForgeEventHelper.java:206)
    at iv.a(NetServerHandler.java)
    at eb.a(SourceFile:136)
    at cg.b(TcpConnection.java:454)
    at iv.d(NetServerHandler.java:141)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
    at com.sk89q.worldguard.bukkit.ConfigurationManager.get(ConfigurationManager.java:203)
    at com.sk89q.worldguard.bukkit.WorldGuardPlayerListener$PlayerMoveHandler.onPlayerMove(WorldGuardPlayerListener.java:90)
    at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:395)
    ... 19 more
2013-01-25 14:08:07 [INFO] [STDERR] Exception in thread "pool-1-thread-14" org.apache.commons.lang.UnhandledException: Plugin WorldGuard v5.6.5 generated an exception while executing task 5
    at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VAsyncTask.run(B4VAsyncTask.java:66)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at com.sk89q.worldguard.bukkit.ConfigurationManager.get(ConfigurationManager.java:203)
    at com.sk89q.worldguard.bukkit.FlagStateManager.run(FlagStateManager.java:68)
    at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
    at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VAsyncTask.run(B4VAsyncTask.java:54)
    ... 3 more

only happened in myscraft dim
Enter Nether won't got that

**Comment by SpoonsJTD** [comment]
It's a bit complicated because both Forge and Bukkit have a completely different API for handling worlds and teleportation. Trying to shoehorn Bukkit into Forge isn't easy, primarily because there is way too much exposed, i.e., too much passing around of java.io.File's and file paths. In a private branch, I had worlds generating, but the directories were all messed up and I couldn't find a good way around it. I don't know the code nearly as well as Keepcalm, but world management is what I am currently focused on.

**Comment by SpoonsJTD** [comment]
The OP should be fixed -- player objects should correctly detect the current dimension/world appropriately.

**Comment by AlexMason** [comment]
Just to let Spoons know, worldedit does not work in seperate dimension, but essentials and worldguard work fine.

**Comment by SpoonsJTD** [comment]
Odd, I have had confirmation that world edit works fine in the Nether, for example, without creating blocks in overworld.

**Comment by AlexMason** [comment]
I was testing this in the mod Twilight Forest, I have yet to test in a Mystcraft Dimension, could be related to twilight forest.  I will do further testing, and let you know.
